services:
  db:
    image: postgres:18-alpine
    container_name: paperless-db
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./backend
    container_name: paperless-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/paperless
      SPRING_DATASOURCE_USERNAME: paperless
      SPRING_DATASOURCE_PASSWORD: paperless
    depends_on:
      - db
      - rabbitmq

  ui:
    build: ./ui
    container_name: paperless-ui
    ports:
      - "80:80"
    depends_on:
      - app

  ocr-worker:
    build: ./ocr-worker
    container_name: ocr-worker
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpassword
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  genai-worker:
    build: ./genai-worker
    container_name: genai-worker
    depends_on:
      - rabbitmq
      - app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: paperless-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.8
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9200 >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  indexing-worker:
    build: ./indexing-worker
    container_name: indexing-worker
    depends_on:
      - rabbitmq
      - elasticsearch
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data: